name: 'proj-signoz'
services:
  nginx:
    network_mode: host
    restart: always
    build:
        context: ./nginx
        dockerfile: Dockerfile.signoz
    image: nginx
    environment:
        DOMAIN: '${DOMAIN}'
        EMAIL_SUPPORT: '${EMAIL_SUPPORT}'
        STAGING_URL: '${STAGING_URL}'
