name: Testing Production

on:
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
  test-production:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create envirioment
        run: |
         set -e
         content="
            DefaultConnection='Server=mssql,1433;Database=finshark;User Id=sa;Password=ch@ng3MeSo0nMan;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;'
            SecretKey='$(tr -dc A-Za-z0-9 </dev/urandom | head -c 128; echo)'
            Host='http://localhost:5246'
            MSSQL_SA_PASSWORD='ch@ng3MeSo0nMan'
          "
          echo "$content" > .env

      - name: Build docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"
      
      - name: Run Database Migrations
        run: |
          set -e
          docker compose -f docker-compose.yml exec -T migrater dotnet tool restore
          docker compose -f docker-compose.yml exec -T migrater dotnet ef database update --verbose